const exercises = [
  { name: "Dumbbell Shrug", category: "Back" },
  { name: "Dumbbell Upright Row", category: "Back" },
  { name: "Barbell Shrug", category: "Back" },
  { name: "Pullups", category: "Back" },
  { name: "Bent-over Row", category: "Back" },
  { name: "Lat Pull-down", category: "Back" },
  { name: "Barbell Back Squat", category: "Legs" },
  { name: "Convetional Deadlift", category: "Legs" },
  { name: "Sumo Deadlift", category: "Legs" },
  { name: "Romanian Deadlift", category: "Legs" },
  { name: "Leg Extension", category: "Legs" },
  { name: "Leg Curl", category: "Legs" },
  { name: "Bulgarian Split Squat", category: "Legs" },
  { name: "Leg Press", category: "Legs" },
  { name: "Barbell Hip Thrust", category: "Glutes" },
  { name: "Glute Kickback", category: "Glutes" },
  { name: "Dumbell Bench Press", category: "Chest" },
  { name: "Pushups", category: "Chest" },
  { name: "Barbell Bench Press", category: "Chest" },
  { name: "Dumbbell Flyes", category: "Chest" },
  { name: "Cable Cross-Over", category: "Chest" },
  { name: "Hammer Curls", category: "Biceps" },
  { name: "Barbell Curls", category: "Biceps" },
  { name: "Ab Crunch", category: "Abdominals" },
  { name: "V-Ups", category: "Abdominals" },
  { name: "Ab Roll-Out", category: "Abdominals" },
  { name: "Wood Chops", category: "Abdominals" },
];
export default exercises;
