export const ROUTES = {
  CREATETEMPLATE: "/createtemplate",
  MYTEMPLATES: "/mytemplates",
  EDITTEMPLATE: "/edittemplate",
  STARTWORKOUT: "/newworkout",
  MYWORKOUTS: "/myworkouts",
  EDITWORKOUT: "/editworkout",
  MYPROFILE: "/myprofile",
  EDITPROFILE: "/editprofile",
  LOGIN: "/login",
  REGISTER: "/register",
  ABOUT: "/about",
  SOCIAL: "/social",
  FEEDS: "/feeds",
};
