export const ROUTES = {
  CREATETEMPLATE: "/createtemplate",
  MYTEMPLATES: "/mytemplates",
  EDITTEMPLATE: "/edittemplate",
  TEMPLATEPREVIEW: "/templatepreview",
  STARTWORKOUT: "/newworkout",
  MYWORKOUTS: "/myworkouts",
  EDITWORKOUT: "/editworkout",
  MYPROFILE: "/myprofile",
  USER: "/user",
  EDITPROFILE: "/editprofile",
  LOGIN: "/login",
  REGISTER: "/register",
  ABOUT: "/about",
  SOCIAL: "/social",
  FEEDS: "/feeds",
  HOME: "/",
  MODERATOR: "/moderator",
};
